config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books
  resources :authors
  resources :carts

  resources :carts do
    member do
      post :add
    end
  end

  resources :carts do
    member do
      post :remove_one_book
    end
  end


  resources :carts do
    member do
      post :remove_item
    end
  end

  get '/my_cart', to: 'carts#index'

  resources :users do 
    member do
      post :block
    end
  end

  resources :users do 
    member do
      post :unblock
    end
  end
  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/authors_book.rb
class AuthorsBook < ApplicationRecord
    belongs_to :author
    belongs_to :book
end
    

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  has_many :cart_items, dependent: :destroy

  scope :published, -> { where(published: true) }

  validates :title, :price, :quantity, presence: true
  validates :published, inclusion: [true, false]

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def calculate_total_price
    price = 0
    cart_items.each do |cart_item|
      price += cart_item.book.price * cart_item.quantity
    end
    return price
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :book
  end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :cart

  validates :email, uniqueness: true, format: {with: /\A^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$\z/ }

  validates :email, :password, :role, presence: true

  validates :password, length: { in: 3..20 } 
  
  enum role: [:user, :admin]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  include Authorizable
  before_action :check_admin_privilages
  before_action :set_author, only: %i[edit update destroy]

	skip_before_action :verify_authenticity_token

	def index
		@authors = Author.all
  end

  def edit
  end

  def update
    if @author.update(author_params)
      redirect_to authors_path, notice: "Author was successfully edited"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_path, notice: "Author was successfully deleted"
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end

  def set_author
    @author = Author.find(params[:id])   
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Authorizable
  before_action :set_book, only: %i[show edit update destroy author]
  before_action :check_admin_privilages, only: %i[destroy edit update]

  def index
    @books = Book.all
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to root_path, notice: "Book was successfully edited"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path, notice: "Book was successfully deleted"
  end

private

  def book_params
    params.permit(:title, :price, :published)
  end

  def set_book
    @book = Book.find(params[:id])
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include Authorizable
  
  before_action :check_if_logged_in
  before_action :set_cart


  def index
  end

  def add
    book = Book.find(params[:id])
    
    if book.quantity == 0
      redirect_back(fallback_location: root_path, alert: "Book is out of stock!") and return
    end
  
    cart_item = @cart.cart_items.find_by(book: book)
  
    if cart_item
      cart_item.increment!(:quantity)
      redirect_back(fallback_location: root_path)
    else
      cart_item = @cart.cart_items.create(book: book, quantity: 1)
      redirect_back(fallback_location: root_path, notice: "Book added to cart")
    end
  end

  def destroy
    current_user.cart.destroy 
    redirect_to my_cart_path, notice: "Cart cleared"
  end

  # reduces the quantity of an item in the shopping cart if quantity reaches 0 it removes it
  def remove_one_book
    cart_item = CartItem.find(params[:id])

    if cart_item.quantity > 1
      cart_item.decrement!(:quantity)
    else
      cart_item.destroy
    end
    redirect_back(fallback_location: root_path)
  end

  # removes cart item from the cart
  def remove_item
    @cart.cart_items.find(params[:id]).destroy

    redirect_back(fallback_location: root_path)
  end

  private

  def set_cart
    @cart = current_user.cart || current_user.create_cart
  end
  
end

app/controllers/concerns/authorizable.rb
module Authorizable
  extend ActiveSupport::Concern
    
  # checks if user is an admin, if not it responses with 401 status
  def check_admin_privilages
    unless logged_in? && current_user.admin?
      render :file => "public/401.html", :status => :unauthorized
    end
  end  

  # checks if user is logged in, if not it responses with 401 status
  def check_if_logged_in
    unless logged_in?
      render :file => "public/401.html", :status => :unauthorized
    end
  end

  # returns current user if he is logged in
  def current_user
    return unless logged_in?
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # checks if user is logged in
  def logged_in?
    session.present?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	skip_before_action :verify_authenticity_token

  def create
    session_params = params.permit(:email, :password)
    @user = User.find_by(email: session_params[:email])
    if @user && @user.authenticate(session_params[:password])
      if @user.blocked?
        redirect_to login_path, alert: "You are blocked, please contact support"
      else
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Welcome! Login Successful"
      end
    else
      redirect_to login_path, alert: "Login failed"
    end
  end

	def destroy
		session.delete(:user_id)
		redirect_to root_path, notice: "Logged out"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Authorizable
  before_action :set_user, only: %i[block destroy unblock]
  before_action :check_admin_privilages, only: %i[index destroy block unblock]

  def index
    @users = User.all
  end

  def new
  end

  def create
    @user = User.create(user_params)
	  if @user.save
	    session[:user_id] = @user.id
	    redirect_to root_path, notice: "Account created"
	  else
	    redirect_to sign_up_path, alert: "Could not create the account"
	  end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: "User deleted"
  end

  def block
    @user.update_attribute(:blocked, true)
    redirect_to users_path, notice: "User #{@user.email} was blocked"
  end

  def unblock
    @user.update_attribute(:blocked, false)
    redirect_to users_path, notice: "User #{@user.email} was unblocked"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    return unless !!session[:user_id]
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/views/authors/_form.html.erb
<%= form_with model: @author do |form| %>
  <div class="row">
    <form class="col s12">
	  <div class="row">
	    <div class="input-field col s12">
	      First Name: <br>
	      <%= text_field_tag :first_name, @author.first_name%>
	    </div>
	    <div class="input-field col s12">
	      Last Name: <br>
	      <%= text_field_tag :last_name, @author.last_name %> 
	    </div>
	  </div>
	  <div class="row">
	    <%= form.submit class: "btn waves-effect waves-light" %>
	  </div>    
	</form>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author: <%= @author.full_name%> </h1>
<%= render "form", author: @author %>

app/views/authors/index.html.erb
<h1 class="center-align">Authors</h1>
<div class="container">
  <table class="centered striped">
    <thead>
      <tr>
        <th>Authors</th>
      </tr>
    </thead>
      <tbody>
      <% @authors.each do |author| %>
        <tr>  
          <td><%= author.first_name %></td>
          <td><%= author.last_name %></td>
          <td><%= button_to "Delete", author, method: :delete, class: "waves-effect waves-light btn-small"%></td>
          <td><%= link_to "Edit", edit_author_path(author), class: "waves-effect waves-light btn-small"%></td>
        </tr>
      <% end %>
      </tbody>
  </table>
</br>
</div>

app/views/books/_footer.html.erb
<footer class="page-footer" style="position: fixed;bottom: 0;left: 0;width: 100%">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h6 class="white-text">Bookstore</h6>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h6 class="white-text">Links</h6>
        <ul>
          <li>
            <a class="grey-text text-lighten-3" href="https://www.facebook.com/"> <i class="material-icons">facebook</i></a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © <%= Date.today.year %> Copyright Text
    </div>
  </div>
</footer>

app/views/books/_form.html.erb
<%= form_with model: @book do |form| %>
  <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s12">
          Title: <br>
          <%= text_field_tag :title, @book.title%>
        </div>
        <div class="input-field col s12">
          Price: <br>
          <%= text_field_tag :price, @book.price %> 
        </div>
        <div class="input-field col s12">
       	  Published?: <br>
          <%= text_field_tag :published, @book.published %> 
        </div>
      </div>
      <div class="row">
        <%= form.submit class: "btn waves-effect waves-light" %>
      </div>    
    </form>
  </div>
<% end %>

app/views/books/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <%= link_to "Logo", root_path, class: "brand-logo" %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if logged_in? && current_user.admin? %>
        <li> <%=link_to "Users", "/users"%> </li>
        <li> <%=link_to "Authors", "/authors"%> </li>
      <% end %>
      <% if logged_in? %> 
        <li><%= link_to "Sign out", "/logout" %> </li>
        <li><%= link_to "My Cart", "/my_cart" %> </li>
      <% else %>
        <li> <%= link_to "Sign Up", "/sign_up" %> </li>
        <li> <%= link_to "Log In", "/login" %> </li>
      <% end %>
    </ul>
  </div>
</nav>
<% if notice %>
<div class="alert card green white-text">
  <div class="card-content">
    <p><i class="material-icons"></i><%= notice %></p>
  </div>
</div>
<% end %>
<% if alert %>
<div class="alert card red white-text">
  <div class="card-content">
    <p><i class="material-icons"></i><%= alert %></p>
  </div>
</div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book: <%= @book.title%> </h1>
<%= render "form", book: @book %>

app/views/books/index.html.erb
<h1 class = "center-align">Books</h1>
<div class="container">
  <table class="centered striped" style="border: 1px solid #000;">
    <thead>
      <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Author</th>
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>  
          <td><%= book.title %></td>
          <td><%= book.price %></td>
          <td> 
            <% if book.authors.present? %>
              <% @authors = book.authors %>
              <% @authors.each do |author| %>
                <%= author.full_name %> </br>
              <% end %> 
            <% end %>
          </td>
          <td><%= book.quantity %></td>
          <td><%= link_to "Inspect this book", book, class: "waves-effect waves-light btn-small"%></td>
          <% if logged_in? %>
            <% if book.quantity <= 0 %>
              <td><%= button_to "Add to cart", add_cart_path(book), class: "waves-effect waves-light btn-small disabled"%></td>
            <% else %>
              <td><%= button_to "Add to cart", add_cart_path(book), class: "waves-effect waves-light btn-small"%></td>
            <% end %>
          <% end %>
          <% if logged_in? && current_user.admin? %>
            <td><%= button_to "Delete", book, method: :delete, class: "waves-effect waves-light btn-small"%></td>
            <td><%= link_to "Edit", edit_book_path(book), class: "waves-effect waves-light btn-small"%></td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 red lighten-3"> <h1>Inspection of the book</h1> </div>
    <div class="col s12 red lighten-3"> <h4>Title: <%= @book.title %></h4> </div>
    <div class="col s12 red lighten-3"> <h4>Price: <%= @book.price %></h4> </div>
    <div class="col s12 red lighten-3">
      <h4>Autohrs: </br>
        <% if @book.authors.present? %>            
  	      <% @authors = @book.authors %>
          <% @authors.each do |author| %>
            <%= author.full_name %> </br>
          <% end %> 
        <% end %>
      </h4>
	</div>
  </div>
</div>

app/views/carts/index.html.erb
<h1 class = "center-align"> My Cart </h1>
<% if @cart.cart_items.present? %>
  <div class="container">
    <table class="centered striped" style="border: 1px solid #000;">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th></th>
          <th>Quantity</th>
          <th></th>
          <th>Price</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cart.cart_items.each do |cart_item| %>
          <% book = cart_item.book %>
          <% authors = book.authors %>
          <tr>
            <td> <%= book.title %> </td>
            <td>
              <% authors.each do |author| %>
                <%= author.full_name %> </br>
              <% end %>
            </td>
            <td> 
              <%= button_to remove_one_book_cart_path(cart_item) do%>
                <i class="material-icons">exposure_neg_1</i> 
              <% end %>
            </td>
            <td> <%= cart_item.quantity %> </td>
            <td>
              <%= button_to add_cart_path(book) do%>
                <i class="material-icons">exposure_plus_1</i> 
              <% end %>
            </td>
            <td> <%= "#{cart_item.quantity} * #{book.price} = #{cart_item.quantity * book.price}" %> </td>
            <td> <%= button_to "Clear this position", remove_item_cart_path(cart_item), class: "waves-effect waves-light btn-small" %> </td>
          </tr>
        <% end %>
        <tr style="border: 1px solid #000;"> <td> Total: <%= @cart.calculate_total_price %> </td> </tr>
      </tbody>
    </table> </br>
    <%= button_to "Clear Cart", @cart, method: :delete, class: "waves-effect waves-light btn-small"%>
    </div>
<% else %>
  <h1> Empty :C </h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book store</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
  </head>
  <body>
    <header>
      <%= render 'books/header' %>
    </header>
    <main>
    </br>
      <%= yield %>      
    </main> 
    <%= render 'books/footer' %>
    <script type="text/javascript" src="js/materialize.min.js"></script>
  </body>
</html>

app/views/users/index.html.erb
<h1 class = "center-align">Users</h1>
<div class="container">
  <table class="centered striped" style="border: 1px solid #000;">
    <thead>
      <tr>
        <th>Users</th>
      </tr>
    </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>  
          <td><%= user.email %></td>
          <td><%= button_to "Delete", user, method: :delete, class: "waves-effect waves-light btn-small"%></td>
            <td>
              <% if user.blocked? %>
                <%= button_to "Unblock", unblock_user_path(user), class: "waves-effect waves-light btn-small"%>
              <%else%>
                <%= button_to "Block", block_user_path(user), class: "waves-effect waves-light btn-small"%>
              <% end %>
            </td>
        </tr>
      <% end %>
      </tbody>
  </table>
</br>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with url: 'sign_up' do |form|%>
  <div class="row">
    <form class="col s12">
	  <div class="row">
	    <div class="input-field col s12">
		  Email: <br>
	      <%= text_field_tag :email %> 
	    </div>
	    <div class="input-field col s12">
		  Password: <br>
	      <%= password_field_tag :password %>		
	    </div>
	  </div>
	  <div class="row">
	    <%= form.submit class: "btn waves-effect waves-light"%>
	  </div>    
	</form>
  </div>
<% end %>